# Generated by Django 4.1.2 on 2023-05-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='database',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='framework',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
