# Generated by Django 4.1.2 on 2023-05-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_database_project_framework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='database',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='framework',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
